language: python
python:
  - 2.7
  - 3.4
  - 3.5
script: make test
notifications:
  email: false
env:
  global:
    - DATABASE_URL='postgres://postgres@localhost/pages'
  matrix:
    - DJANGO='django~=1.7.0'
    - DJANGO='django~=1.8.0'
install:
  - psql -c 'CREATE DATABASE pages' -U postgres
  - pip install -r test_requirements.txt
  - pip install $DJANGO
